name: "Build"
description: "Builds a node project and caches its dependencies"

inputs:
  node-version:
    description: "Node version"
    type: "string"
    required: false
    default: "20.x"

  build-artifact-path:
    description: "Paths to include in build artifact"
    type: "string"
    required: false
    default: |
      .
      !**/.env
      !**/.env*.local
      !**/.git/
      !**/node_modules/

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: ${{ inputs.node-version }}
        registry-url: "https://registry.npmjs.org"
        cache: "npm"

    - name: Install dependencies
      run: npm ci
      shell: bash

    - name: Build project
      run: npm run build
      shell: bash

    - uses: actions/upload-artifact@v3
      with:
        name: build-${{ github.sha }}
        retention-days: 1
        path: ${{ inputs.build-artifact-path }}
