name: "Build"
description: "Builds a node project and caches its dependencies"

inputs:
  node-version:
    description: "Node version"
    type: "string"
    required: false
    default: "18.x"

  build-artifact-path:
    description: "Node version"
    type: "string"
    required: false
    default: |
      .
      !.git/
      !node_modules/

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: ${{ inputs.node-version }}
        registry-url: "https://registry.npmjs.org"

    - name: Restore cached dependencies
      id: npm-cache-restore
      uses: actions/cache@v3
      with:
        path: node_modules
        key: ${{ hashFiles('package-lock.json', 'package.json') }}

    - name: Install dependencies
      if: steps.npm-cache-restore.outputs.cache-hit != 'true'
      run: npm ci
      shell: bash

    - name: Build project
      run: npm run build
      shell: bash

    - uses: actions/upload-artifact@v3
      with:
        name: build-${{ github.sha }}
        retention-days: 1
        path: ${{ inputs.build-artifact-path }}
